# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
