# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='activities',
            field=models.TextField(max_length=200),
        ),
    ]
